name: build

on: push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, macos-10.15, macos-11]

    runs-on: ${{ matrix.os }}

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: install dependencies
      if: startsWith(matrix.os, 'ubuntu')
      run: >
        sudo apt-get install
        build-essential
        pkg-config
        libncurses-dev
        libfaad-dev libmp4v2-dev
        libavcodec-dev libavformat-dev libavutil-dev
        libflac-dev
        libid3tag0-dev libmad0-dev
        libmpg123-dev
        libopusfile-dev
        libsndfile1-dev
        libvorbis-dev
        libwavpack-dev
        libasound2-dev
        libao-dev
        portaudio19-dev
        libpulse-dev
        libsndio-dev

    - name: install dependencies
      if: startsWith(matrix.os, 'macos')
      run: >
        brew install
        pkg-config
        faad2 mp4v2
        ffmpeg
        flac
        libid3tag mad
        mpg123
        opusfile
        libsndfile
        libvorbis
        wavpack
        libao
        portaudio
        pulseaudio

    - name: configure
      run: ./configure

    - name: build
      run: make

    - name: install
      run: sudo make install
