name: build

on: push

jobs:
  ubuntu:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-24.04]

    runs-on: ${{ matrix.os }}

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: install dependencies
      run: >
        sudo apt-get update &&
        sudo apt-get install
        build-essential
        pkg-config
        libncurses-dev
        libavcodec-dev libavformat-dev libavutil-dev
        libflac-dev
        libid3tag0-dev libmad0-dev
        libmpg123-dev
        libopusfile-dev
        libsndfile1-dev
        libvorbis-dev
        libwavpack-dev
        libasound2-dev
        libao-dev
        portaudio19-dev
        libpulse-dev
        libsndio-dev

    - name: configure
      run: ./configure

    - name: build
      run: make

    - name: install
      run: sudo make install

  macos:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-14, macos-15]

    runs-on: ${{ matrix.os }}

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: install dependencies
      run: >
        brew update &&
        brew upgrade &&
        brew install
        pkgconf
        faad2 mp4v2
        ffmpeg
        flac
        libid3tag mad
        mpg123
        opusfile
        libsndfile
        libvorbis
        wavpack
        libao
        portaudio
        pulseaudio
        || true

    - name: configure
      run: ./configure

    - name: build
      run: make

    - name: install
      run: sudo make install

  dragonfly:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: run vm
      uses: vmactions/dragonflybsd-vm@v1
      with:
        usesh: true
        prepare: >
          pkg install -y
          pkgconf
          faad2 mp4v2
          ffmpeg
          flac
          libid3tag libmad
          mpg123
          opusfile
          libsndfile
          libvorbis
          wavpack
          libao
          portaudio
          sndio
        run: |
          uname -a
          sed -i '' s,curses.h,ncurses/ncurses.h, compat.h configure screen.c
          sed -i '' s,-lcurses,-lncurses, configure
          CPPFLAGS=-I/usr/local/include LDFLAGS=-L/usr/local/lib \
            ./configure
          make
          make install

  freebsd:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: run vm
      uses: vmactions/freebsd-vm@v1
      with:
        usesh: true
        prepare: >
          pkg install -y
          pkgconf
          faad2 mp4v2
          ffmpeg
          flac
          libid3tag libmad
          mpg123
          opusfile
          libsndfile
          libvorbis
          wavpack
          libao
          portaudio
          pulseaudio
          sndio
        run: |
          uname -a
          CPPFLAGS=-I/usr/local/include LDFLAGS=-L/usr/local/lib \
            ./configure
          make
          make install

  netbsd:
    strategy:
      fail-fast: false
      matrix:
        ffmpeg: [ffmpeg3, ffmpeg4, ffmpeg5, ffmpeg6, ffmpeg7]

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: run vm
      uses: vmactions/netbsd-vm@v1
      with:
        prepare: >
          pkg_add
          pkg-config
          faad2 mp4v2
          flac
          libid3tag libmad
          mpg123
          opusfile
          libsndfile
          libvorbis
          wavpack
          alsa-lib
          libao
          portaudio
          pulseaudio
          ${{ matrix.ffmpeg }}
        run: |
          uname -a
          CPPFLAGS='-I/usr/pkg/include -I/usr/pkg/include/faad2' \
            LDFLAGS='-L/usr/pkg/lib -Wl,-R/usr/pkg/lib' \
            PKG_CONFIG_PATH=/usr/pkg/lib/${{ matrix.ffmpeg }}/pkgconfig \
            ./configure
          make
          make install
